### ISSUE TITLE
No se muestra U+1F550

### ISSUE THREAD

**Issue by M42** [coDual/codual.github.io#1]
En Firefox 45, imagino que con las fuentes por defecto, no se muestra "🕐" más que como un recuadro de Unicode. No sé si podemos asumir que se mostrará en la mayoría de navegadores; o se puede pedir de alguna forma al navegador que use una fuente más completa.

Esto además ocurre en el blog, no en esta issue, por ejemplo. Quizá sea sólo cuestión de elegir las fuentes.

**Comment by tzae** [comment]
La fuente que utilizamos es [Open Sans](https://www.google.com/fonts/specimen/Open+Sans) de Google Fonts aunque supongo que no tendrá soporte para emoji. No es problema de Firefox, yo puedo verlo sin problemas.

Nuestras opciones son:
- Usar [jemoji](https://github.com/jekyll/jemoji)
- Usar otra fuente con soporte para Unicode ([Google Noto Font?](https://www.google.com/get/noto/))

**Comment by tzae** [comment]
Solucionado usando [jemoji](https://help.github.com/articles/emoji-on-github-pages).
